version: '3.3'

services:
    nginx:

        image: nginx:latest

        container_name: nginx

        ports:
            - "80:80"
            - "443:443"

        volumes:
            - /projects/company-tree/docker-compose/nginx/config:/etc/nginx/conf.d
            - /projects/company-tree/docker-compose/nginx/logs:/var/log/nginx/
            - /projects/company-tree:/var/www/company-tree

        links:
            - php

    mysql:

        image: mysql:5.7

        ports:
            - "3306:3306"

        container_name: mysql

        environment:

            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}

        volumes:
            - /projects/company-tree/docker-compose/mysql:/var/lib/mysql

        command: "--innodb_use_native_aio=0"

    php:

        build: ./php

        container_name: php-fpm

        volumes:
            - /projects/company-tree:/var/www/company-tree

        links:
            - mysql


    phpmyadmin:

        image: phpmyadmin/phpmyadmin

        container_name: phpmyadmin

        environment:
            - PMA_HOST=mysql
            - MYSQL_USERNAME=root
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

        ports:
            - "8090:80"

        links:
            - mysql:db
